### ISSUE TITLE
Can `read` to a type which has nested `Seq` field referenced to self

### ISSUE THREAD

**Issue by freewind** [lihaoyi/upickle#82] opened 2015-04-11 06:45 UTC
My code: 

```scala
import upickle._
read[Category](json)  // !!! can't compile
```

and related code is:

```scala
case class Category(id: String, name: String, projects: Seq[Project], description: Option[String] = None)

case class Project(id: String,
                   name: String,
                   linkGroups: Seq[LinkGroup] = Nil,
                   description: Option[String] = None,
                   stars: Option[Int] = None,
                   subProjects: Seq[Project] = Nil)

case class LinkGroup(id: String, name: String, links: Seq[Link] = Nil)

case class Link(id: String, name: Option[String] = None, url: String, description: Option[String] = None, showUrl: Boolean = true)
```

It can't compiled and failed on this line:

https://github.com/lihaoyi/upickle/blob/master/upickle/shared/src/main/scala/upickle/Macros.scala#L32

```scala
if (tpe.typeSymbol.fullName.startsWith("scala."))
        c.abort(c.enclosingPosition,s"this may be an error, can not generate Reader[$tpe <: ${tpe.typeSymbol.fullName}]")
```

I added some logging to print the value of `tpe.typeSymbol.fullName`, and found it:

    Warning:scala: tpe.typeSymbol.fullName: scala.collection.Seq

Not sure where is wrong, and how to fix it?

**Comment by freewind** [comment] 2015-04-11 06:51
I found if I removed the `subProjects: Seq[Project] = Nil` from `Project`, the compilation will be good

**Comment by tindzk** [comment] 2015-04-13 11:08
This is a duplicate of #30.

**Comment by lihaoyi** [comment] 2015-04-16 22:25
Yep, let's keep the discussion in one place

**Closed by lihaoyi** 2015-04-16 22:25 UTC
Labels: duplicate
