### ISSUE TITLE
macro fail with nested class with scala containers

### ISSUE THREAD

**Issue by MasseGuillaume** [lihaoyi/upickle#76] opened 2015-03-09 22:33 UTC
```scala
case class Bucket(name: String, objects: Seq[S3Node])
sealed trait S3Node
case class S3Folder(path: String, nodes: Seq[S3Node]) extends S3Node
case class S3File(path: String) extends S3Node
import upickle._
write(Bucket("a", Seq(S3Folder("b", Seq(S3File("c"))))))
java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:151)
        at upickle.Macros$.macroWImpl(Macros.scala:49)
              write(Bucket("a", Seq(S3Folder("b", Seq(S3File("c"))))))
                     ^
```

**Comment by tindzk** [comment] 2015-03-09 22:54
Isn't this a duplicate of #30?

**Comment by lihaoyi** [comment] 2015-03-09 22:55
Probably, let's move it over since it looks similar

**Closed by lihaoyi** 2015-03-09 22:55 UTC
